language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"

install:
  - python setup.py -q install

script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then make test pep8; else make ci; fi" 

after_success:
  - coveralls